### PR TITLE
Open and close output on each iteration

### PR DESCRIPTION
**Pull request by magnusuMET**

### CODE REVIEW

**Review by heikoklein — COMMENTED** [review]
The changes look ok and will work, I guess.
I don't really like the 
```
  type(common_var), save :: varid
  type(common_dim), save :: dimid
```
I don't think that the netcdf-library guarantees that varid/dimid keep identical when opening the file again. Using `nf90_inq_dim/var` is cheap and safer, and the documented way.

**Comment by magnusuMET** [comment]
That is an excellent catch, netcdf does not guarantee ordering of variables or dimensions. Quite a lot of boilerplate to implement, but variables are now acquired on every iteration

**Comment by heikoklein** [comment]
ap, b and k are optional in nc_set_vtrans, but you enforce them during inq-ing if I see that correctly.

really lots of boilerplate code. I would love to see something like initialize_or_inquire_output(is_initialized=True/False), where you replace every nf90_def_var, with a def_or_inq_var(is_initialized...), so that the definitions/inquires are at the same place and we don't need to guess if we require a variable or not.

**Comment by magnusuMET** [comment]
Corrected `vtrans` to optional variables

**Comment by heikoklein** [comment]
`make test` fails with 
```
 *READFIELD* No model level data available
 ------- SNAP ERROR EXIT -------
ERROR STOP ------- SNAP ERROR EXIT -------

Error termination. Backtrace:
#0  0x7fcc5922ed8a in ???
#1  0x7fcc5922f925 in ???
#2  0x7fcc592309fa in ???
#3  0x404e4f in snap_error_exit
	at /home/heikok/Programme/Models/snap/src/test/snap_batch_copy.F90:1054
#4  0x405ce5 in bsnap
	at /home/heikok/Programme/Models/snap/src/test/snap_batch_copy.F90:1015
#5  0x40348c in main
	at /home/heikok/Programme/Models/snap/src/test/snap_batch_copy.F90:146
```

Not sure when `make test` started failing.

It would also be a cheap and good idea to add the coordinate-axes to the tests.

**Pull request merged**
