### PR TITLE
CMake integration

### PR DESCRIPTION
**Pull request by magnusuMET**
Using CMake as a build system has several advantages over the current makefiles:

##  Faster
Clean build:
cmake (RelWithDebInfo): 14.4s
old make: 24.3s
In addition, `make -j`now works as expected,
cmake (RelWithDebInfo, make -j): 5.0s

## Build types
The selection of compiler flags can now be better adapted per build type, and relevant flags can be grouped together. There is no longer to create a custom `current.mk`.

## Ease of use
CMake allows easier out-of-tree builds, and better dependency handling. Packaging and testing is now an integral part of the build system.

## Remains:
* drhook integration
* static/shared milib
* SnapPy packaging
* Testing for more systems
* Removal of makefiles
* Using nf-config where available
* Overriding netcdf library

### CODE REVIEW

**Comment by heikoklein** [comment]
I still don't see the reason for using cmake. cmake helps doing automatic configurations which we don't want to use in HPC environments. We pick compiler, options and modules carefully. Each platform (HPC-like machine) has a hand-selected set of rules. I hardly ever use the first library in the path, often, the one in the path is not available on the runtime-platform. With cmake, we will need one CMakelist per platform, containing the information which is currently in the *.mk files. In addition, we need to run at least one non-trivial command (cmake +options) extra when making changes, e.g. to the compiler flags.

Fixes for make -j and the make doc targets are nice to have, but can be achieved by adapting the makefiles. 

Why RelWithDebinfo is faster I don't understand, all it does is changing optimization flags - something I definitely not want.

Your cmake-setup is faster because you don't completely recompile the different programs (naccident,traj,volcano) but only the currently minimum required objects (snap,forward,forward_dx). You will anyway only need naccident. traj should not be used, volcano is superseeded by eemep, bomb and naccident are identical. So the only target needed is make naccident_install, anything else is legacy. make in naccident takes 7s on my few year old machine.

Your netcdf-detection will not work for static linking.


The code-changes with public and implicit none are very nice and I would like to accept independently.

**Comment by magnusuMET** [comment]
> With cmake, we will need one CMakelist per platform, containing the information which is currently in the *.mk files.

The *.mk files will be replaced with the invocation of cmake with different flags. This makes it simple to run on unknown platforms (which will require special care anyway, admittedly).

> we need to run at least one non-trivial command extra when making changes, e.g. to the compiler flags.

Make will automatically rerun cmake when the flags are changed. Currently, the makefiles require running `make clean && make` if current.mk is modified.

> Fixes for make -j

This requires manual dependency checking (modules must be compiled first), but is doable

> make doc

We would need to spend time on documentation to make this a useful target. Right now it is only useful for quickly examining the call graphs

> traj should not be used, volcano is superseeded by eemep, bomb and naccident are identical. So the only target needed is make naccident_install, anything else is legacy.

Should some of these be deprecated?

> Your netcdf-detection will not work for static linking.

This can be added

**Comment by magnusuMET** [comment]
It seems the only true advantages of cmake are out-of-tree builds and correct recompiles when a file changes. Should the compiler flags be backported and this PR closed?

**Comment by heikoklein** [comment]
Yes, please backport the compiler flags and close the issue.

**Pull request closed without merging**
