### PR TITLE
Job script now backs up old runs before running

### PR DESCRIPTION
**Pull request by babrodtk**
This PR avoids erroneously reusing old results on failed runs. 

This moves existing eemep_{hour,hourInst,day}.nc to a timestamped file before starting new run. Should not really be a big issue wrt space as these files are not too large.

The backup files are cleaned up after some time automatically with the command below (find -mtime +2 -delete).

### CODE REVIEW

**Comment by babrodtk** [comment]
This PR still needs to be checked before merging. I'm not fully confident in it yet. 

Regarding the status-check, I believe it is because of eemepModelRunner:147-154, which expects an exception to be thrown is something is wrong (compare with ModelRunner::work()). I believe the eemepModelRunner simply uploads, runs, and downloads without checking for errors in any of the stages. I'll fix this also in this PR shortly.

**Comment by babrodtk** [comment]
This PR became much larger than originally intended.
- Changes scp to rsync in SSHConnection (same ssh parameters)
- File ages are checked in ModelRunner. Most outdated-thresholds are set quite loose (e.g., 2 hours). Will not catch every single error, but will catch an outdated run of more than 2 hours
- Check of sha256sum of files added to make sure remote files are the intended files. This may not be required (the rsync should take care of it), and can easily be removed if you think it is overkill
- Test now runs again. Last run was when frost was still an active machine. 
- eemepModelRunner now calls ModelRunner.work() instead of the individual methods that work() calls.

**Comment by heikoklein** [comment]
rsync and sha256sum are external dependencies, but they are easily available, so not a big problem.

Which problem do you want to solve with rsync?
Which problem do you want to solve by sha256sum?

**Comment by babrodtk** [comment]
Q: Which problem do you want to solve with rsync?
A: Copying of meteorology files which already exist. This should save a significant amount of bandwidth use

Q: Which problem do you want to solve by sha256sum?
A: Check that the uploaded files are what we expect them to be. This will trigger an error if a wrong file is uploaded or overwritten. 

Both are easy to remove from the PR if you don't like them:)

**Comment by heikoklein** [comment]
Not really convinced that we have or solve these problems.

The sha256sum solution might suggest that we have tested that the producer (ecdiss) and the consumer (eemep) see the same file. With distributed filesystems, we have at least 4 copies (ecdiss->obj-store, obj-store->scp-job, scp-job->objStore, objStore->emepNode) which we don't check, just to check one copying (which has build-inn checks). 

rsync rather than scp might be a nice extension to the SSHConnection when we have a case where we often need to rerun the model with the same meteorology. We haven't been using SSHConnection the last 2 years, and have no plans to do so as long as we use PPI which has a DirectConnection. Difficult to see side-effects if not in active use...

**Comment by babrodtk** [comment]
OK, I'll remove them. The reason for the rsync change was by following the old Frost code which used that, and I apparently did not realize that PPI used the DirectConnection.

**Comment by babrodtk** [comment]
I have checked the source cod of this again. Assume it is fine to merge. Will  merge and check that volcano still works as expected.

**Comment by babrodtk** [comment]
This merge will not affect the operational code until rolled out as new package / external_projects updated

**Pull request merged**
