### PR TITLE
Fimex read

### PR DESCRIPTION
**Pull request by heikoklein**
Already useful and first tests give identical (visual) results on meps. Much less error-prone with respect to units or other parameters, e.g. ensemble/non-ensemble data or dummy-height dimension. Still compiles without fimex.

### CODE REVIEW

**Comment by magnusuMET** [comment]
Is it possible to support automatically read grid parameters from fimex? (To drop `gparams?)

**Comment by heikoklein** [comment]
> Is it possible to support automatically reading grid parameters from fimex? (To drop `gparams`?)

I can't read attributes directly from fimex-fortran. I think about a solution where one creates a template-netcdf file, SNAP reads that template with netcdf as now. But that will be another commit.

**Comment by heikoklein** [comment]
Why did you remove the dealloc(zfield) in the 'doxygen lint' commit? zfield can change size depending on request, so it should be allocated/deallocated on each request. (didn't run a test yet)

**Comment by magnusuMET** [comment]
zfield is a local variable in fi_checkload{1,2,3}d, and will be deallocated on return. Should the fields be `save`?

**Comment by heikoklein** [comment]
zfield should definitely not be `save`.
zfield is allocated in fi_checkload_intern and must be deallocated in fi_checkload{1,2,3}d. This usage pattern is not obvious and an explicit dealloc makes it clearer. I'm also not sure how well compiler support for cross subroutine alloc/dealloc are.

We could rather remove the `if ( .not.allocated(zfield)) ` (Fortran2003, Intent(OUT) are deallocated on entry) than the dealloc.

**Comment by magnusuMET** [comment]
Reading through the standard (Deallocation of allocatable variables, Finalization), all allocatables that are not saved will be automatically deallocated (unless program exits). I would hope compilers are up to date, but I will add back the explicit deallocs, especially as we are not yet compiling with -std=f2008.

**Comment by magnusuMET** [comment]
We should probably abstract some of the common code parts between felt/fimex/netcdf into a common readfield module.

**Comment by heikoklein** [comment]
> We should probably abstract some of the common code parts between felt/fimex/netcdf into a common readfield module.

Yes and no. I would like to simplify the time-handling in an own module and move it out of the mixture of snap.F90 and readfield*.f90. But that is definitely another enhancement/commit.

**Pull request merged**
