### PR TITLE
Round upwards for short release periods

### LINKED ISSUE #35: No particles release when release-time is < 1h
Whenever using a linear release with less than 1h, no model-particles are released in SNAP:

```
 Title:      Kola 2020 11 06 13
 Summary:     Starttime: 2020-11-06T13:00. Release Pos (lat, lon): ( 67.5,  32.5). Release CS137 (hour, Bq/s): (  0.0, 2.60E+11) (  0.8, 2.60E+11)
 istep,nplume,npart:            0           0           0
input data: 2020 11 06 12  prog=   0
input data: 2020 11 06 15  prog=   0
 istep,nplume,npart:           12           0           0
```

### PR DESCRIPTION
**Pull request by magnusuMET**
Previous behaviour was to truncate real to integer, we now cast upwards in all cases

Fixes #35

### CODE REVIEW

**Comment by heikoklein** [comment]
Tested the example and particles are now emitted, but unfortunately, I get now emissions for a complete hour, not for 45min, i.e. totalbq in the log-file gives: 9.36000142E+14 = 2.6e11*60*60 rather than 7e14=2.6e11*60*45

**Comment by magnusuMET** [comment]
Integration tests have been added for the following cases:
* Start at 0:15 (fails with a clear error message)
* Start at 0:00, end at 1:45 (previously failing)
* Start at 0:00, end at 0:30, resume at 1:15, end at 3:00

The tests parses the logfile to determine the current step and number of particles released.

**Comment by heikoklein** [comment]
The code looks very good, but I get a lot of errors when running the tests:
```
Traceback (most recent call last):
  File "/home/heikok/Programme/Models/snap/src/test/snap_forward_test.py", line 165, in test_end_non_integer_hour
    with open(self.input, "r") as f:
TypeError: invalid file: PosixPath('/home/heikok/Programme/Models/snap/src/test/data/snap.input_releasetests')
```
The file exists, no idea why I get this errror? I get it for all 3 tests.


I get also: 

```
FAIL: test_runfimex (snap_forward_test.SnapEcEMEPForwardTestCase)
...
AssertionError: False is not true : Cs137_acc_wet_deposition at time(7): 0.037677470594644547 !~ 0.026047123596072197 within 20%
```
which is most likely a numerical error due to changed compiler? It's on my old test, so that needs some refinement for very small values.

**Comment by magnusuMET** [comment]
The first of the issues is hopefully fixed now, could be due to an older python edition (I'm using 3.6.9).

For the second issue: Should we drop all values below XX or add a fixed RNG for consistency between compiler versions?

**Comment by heikoklein** [comment]
I agree that the numeric issue is not part of this PR. But the other 3 tests are still failing for me:
```
Traceback (most recent call last):
  File "/home/heikok/Programme/Models/snap/src/test/snap_forward_test.py", line 133, in test_start_half_hour
    subprocess.check_call([self.snap.resolve().as_posix(), "snap.input"], cwd=tmp)
  File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'PosixPath' object to str implicitly
```

**Comment by magnusuMET** [comment]
python3.5 is a bit finicky with `pathlib`, paths are not supported everywhere. Paths should be fixed now

**Comment by heikoklein** [comment]
Still errors:
```
Traceback (most recent call last):
  File "/home/heikok/Programme/Models/snap/src/test/snap_forward_test.py", line 158, in test_start_half_hour
    shutil.rmtree(tmp)
  File "/usr/lib/python3.5/shutil.py", line 465, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 463, in rmtree
    orig_st = os.lstat(path)
TypeError: lstat: illegal type for path parameter

```

**Comment by magnusuMET** [comment]
Please try again.

We should set up some CI and minimal versions of all associated libraries to test against to avoid these errors.

**Review by heikoklein — APPROVED** [review]
Working well, please merge.

**Pull request merged**
